/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'carlos' at '12/7/15 11:20 PM' with Gradle 2.1
 *
 * @author carlos, @date 12/7/15 11:20 PM
 */

import spock.lang.Specification

class ComicReminderTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        ComicReminder lib = new ComicReminder()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
